name: 07 - Using Expressions

on:
  workflow_dispatch:
    inputs:
      debug:
        description: 'Enable debug mode'
        type: boolean
        default: false

run-name: 07 - Using Expressions | DEBUG - ${{ inputs.debug && 'ON' || 'OFF' }}

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Print start-up data
        if: inputs.debug
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo "Ref: ${{ github.ref }}"
          echo "SHA of the commit: ${{ github.sha }}"
          echo "Runner OS: ${{ runner.os }}"

      - name: Print when triggered from main
        if: inputs.debug && github.ref == 'refs/heads/main'
        run: |
          echo "I was triggered from the main branch"

      - name: Greeting
        run: echo "Hello, world!"