name: 09 - Using Functions

on:
  workflow_dispatch:

jobs:
  echo1:
    runs-on: ubuntu-latest
    steps:
      - name: Print PR title
        run: echo "${{ github.event.pull_request.title }}"
      - name: Print PT labels
        run: |
          echo << EOF
          ${{ toJSON(github.event.pull_request.labels) }}
          EOF
      - name: Bug step
        if: ${{ !cancelled() && contains(github.event.pull_request.title, 'fix') }}
        run: echo "I am a bug"
      - name: I will execute
        if: ${{ success() }}
        run: echo "I will print if previous steps succeed"
      - name: I will execute
        if: ${{ failure() }}
        run: echo "I will print if any previous steps fail"
      - name: I will execute
        if: ${{ !cancelled() }}
        run: echo "I will always print unless the workflow is cancelled"
      - name: I will execute when the workflow is cancelled
        if: ${{ cancelled() }}
        run: echo "I will print if the workflow is cancelled"