name: 17 - 3 - Custom Actions - Docker

on:
  workflow_dispatch:
    inputs:
      url:
        type: choice
        description: 'The URL to ping'
        options:
          - 'https://www.google.com'
          - 'https://www.invalid-fafafa.com'
          - 'fasfasfaegsb'
      max_trials:
        type: number
        description: 'The maximum number of trials to attempt'
        default: 10
      delay:
        type: number
        description: The delay in seconds between each trial
        default: 5

jobs:
  ping-url:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Ping URL
        id: ping-url
        uses: ./.github/actions/docker-ping-url
        with:
          url: ${{ inputs.url }}
          max_trials: ${{ inputs.max_trials }}
          delay: ${{ inputs.delay }}
      - name: Print ping URL output
        run: |
          echo "URL reachable: ${{ steps.ping-url.outputs.url-reachable }}"