name: 18 - 3 - Reusable Workflows

on:
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/18-1-reusable-workflow.yaml
    with:
      target-directory: VALUE

  e2e-tests:
    needs: deploy
    uses: pedroalves91/gh-actions-example-e2e/.github/workflows/e2e.yaml@main