name: Test workflow

on:
  workflow_dispatch:
    inputs:
      run:
        type: boolean
        description: run
        default: true

jobs:
  first:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: echo "1"

  second:
    runs-on: ubuntu-latest
    needs: first
    if: inputs.run
    steps:
      - name: step2
        run: echo "2"

  third:
    runs-on: ubuntu-latest
    if: ${{ success() || (needs.first.result == 'success' && needs.second.result == 'skipped') }}
    needs:
      - first
      - second
    steps:
      - name: step3
        run: echo "3"