name: Test workflow

on:
  workflow_dispatch:
    inputs:
      run:
        type: boolean
        description: run
        default: true

jobs:
  first:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: echo "job 1"

  second:
    runs-on: ubuntu-latest
    needs: first
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - name: step2
        run: echo "job 2"

  third:
    runs-on: ubuntu-latest
    if: ${{ always() || always() && needs.second.result == 'skipped' }}
    needs:
      - first
      - second
    steps:
      - name: step3
        run: echo "job 3"